---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: linux
      dist: bionic
      sudo: required
      python: "3.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install yamllint

  # Check ansible version
  - ansible --version
  - 'dpkg -l | grep "^hi" || /bin/true'
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - 'dpkg -l | grep "^hi" || /bin/true'

script:
  - sudo apt list --upgradable
  - "find . -name '*.yml' -print0 | xargs -0 yamllint -c galaxy-yamllint.yaml"
  # Basic role syntax check
  - cd tests
  - ansible-playbook test.yml -i inventory --syntax-check
  - ./run_tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
