---
language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
env:
  - ANSIBLE_PIP='ansible'
  - ANSIBLE_PIP='ansible==2.8.*'
  - ANSIBLE_PIP='ansible==2.9.*'
dist: bionic

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install "$ANSIBLE_PIP"
  - pip install yamllint

  # Check ansible version
  - ansible --version
  - sudo apt-get update

script:
  - "find . -name '*.yml' -print0 | xargs -0 yamllint -c galaxy-yamllint.yaml"
  # Basic role syntax check
  - cd tests
  - ansible-playbook test.yml -i inventory --syntax-check
  - ./run_tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
